/*DROP TYPE TBL_INTAKE_SHELTERS;
DROP TYPE ROW_INTAKE_SHELTERS;
*/
CREATE TYPE ROW_INTAKE_SHELTERS AS OBJECT(
INTAKE_ANIMAL_ID VARCHAR2(30 BYTE),
INTAKE_TIME TIMESTAMP(6),
S_TITLE VARCHAR2(100 BYTE));
/


CREATE TYPE TBL_INTAKE_SHELTERS IS TABLE OF ROW_INTAKE_SHELTERS;
/

CREATE OR REPLACE FUNCTION INTAKE_SHELTERS(AN_ID IN VARCHAR2, IN_YEAR IN VARCHAR2)
RETURN TBL_INTAKE_SHELTERS
PIPELINED
IS
  CURSOR MY_CURSOR IS
    SELECT INTAKE.ANIMAL_ID, INTAKE.INTAKE_DATETIME, SHELTERS.SHELTER_TITLE
    FROM INTAKE, shelters
    WHERE intake.shelter_id = shelters.shelter_id AND
    EXTRACT(YEAR FROM intake_datetime) >= IN_YEAR AND
    AN_ID = INTAKE.ANIMAL_ID;
BEGIN
FOR rec in MY_CURSOR
  LOOP
    PIPE ROW(ROW_INTAKE_SHELTERS(rec.ANIMAL_ID, rec.INTAKE_DATETIME, rec.SHELTER_TITLE));
  END LOOP;

END INTAKE_SHELTERS;












