CREATE OR REPLACE TRIGGER ANIMALS_NAMES
    BEFORE INSERT OR UPDATE
    ON ANIMALS
    FOR EACH ROW
BEGIN
    IF (:new.ANIMAL_NAME IS NULL)
    THEN
        :new.ANIMAL_NAME := 'NO_NAME';
    END IF;
END;
/

Insert into ANIMALS (ANIMAL_ID,ANIMAL_TYPE,APPROXIMATE_BREED,ANIMAL_NAME) values ('A7122222211','Cat','Мейн кун',NULL);